services:
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    networks:
      - bloombot
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bloombot
    logging:
      options:
        max-size: '20m'
        max-file: '3'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  bloombot:
    container_name: bloombot
    env_file:
      - .env
      - .env.development.local
    image: favware/bloombot:latest
    logging:
      options:
        max-size: '1g'
        max-file: '3'
    networks:
      - bloombot
    restart: always
    tty: true

volumes:
  postgres-data:

networks:
  bloombot:
